### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by martoio** [ross1979/prj-rev-bwfs-dasmoto#2]
Make sure you add the ``alt`` attribute to your images to maintain accessibility for all audiences of the page (particularly visually-impaired users). Remember to add it even in these simple projects and it will become a habit. (Hint: as long as you have the ``alt`` attribute with something semi-meaningful, we'll be happy with it).
For more info: https://www.codecademy.com/articles/accessibility

https://github.com/ross1979/prj-rev-bwfs-dasmoto/blob/cd22c20d85cf05c78c8630fff72382309501cc76/Dasmoto/index.html#L12

**Comment by ross1979** [comment]
Very helpful, as i'm new to this it's not something I would have immediately thought of, but I can see the benefits.
