### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by martoio** [ross1979/prj-rev-bwfs-dasmoto#3]
Make sure you implement proper indentation in your code to ease readability and show any parent-child relationships between the elements.
https://www.granneman.com/webdev/coding/formatting-and-indenting-your-html/

https://github.com/ross1979/prj-rev-bwfs-dasmoto/blob/cd22c20d85cf05c78c8630fff72382309501cc76/Dasmoto/index.html#L8-L10

**Comment by ross1979** [comment]
Noted, I must get better at this.
